import React, { useCallback } from 'react';
import { createCanvas, clearCanvas, drawGrid, downloadCanvas } from '../utils/canvasHelpers';
import { renderModules, getUniqueModuleTypes } from './ModuleExtractor';
import { renderBitmapText } from '../utils/bitmapFont';

export default function ExportButton({ modules, rows, cols, primaryColor, secondaryColor, bgColor, moduleScale }) {
  const handleExport = useCallback(() => {
    if (!modules) return;

    const width = 1200;
    const height = 1600;
    const canvas = createCanvas(width, height);
    const ctx = canvas.getContext('2d');
    clearCanvas(ctx, bgColor);

    const uniqueTypes = getUniqueModuleTypes(modules);
    let y = 40;

    // Title
    ctx.fillStyle = primaryColor;
    ctx.font = 'bold 28px monospace';
    ctx.fillText('FLEXIBLE VISUAL SYSTEM', 40, y);
    y += 20;

    ctx.fillStyle = '#888';
    ctx.font = '14px monospace';
    ctx.fillText('System Sheet — Generated Export', 40, y);
    y += 40;

    // Divider
    ctx.fillStyle = primaryColor;
    ctx.fillRect(40, y, width - 80, 2);
    y += 30;

    // Section: Color Palette
    ctx.fillStyle = '#888';
    ctx.font = '11px monospace';
    ctx.fillText('COLOR PALETTE', 40, y);
    y += 20;

    const colors = [
      { label: 'Primary', color: primaryColor },
      { label: 'Secondary', color: secondaryColor },
      { label: 'Background', color: bgColor },
    ];

    colors.forEach((c, i) => {
      const x = 40 + i * 160;
      ctx.fillStyle = c.color;
      ctx.fillRect(x, y, 60, 60);
      ctx.strokeStyle = '#333';
      ctx.strokeRect(x, y, 60, 60);
      ctx.fillStyle = '#888';
      ctx.font = '10px monospace';
      ctx.fillText(c.label, x, y + 76);
      ctx.fillText(c.color, x, y + 90);
    });
    y += 110;

    // Section: Module Library
    ctx.fillStyle = '#888';
    ctx.font = '11px monospace';
    ctx.fillText('MODULE LIBRARY', 40, y);
    y += 20;

    uniqueTypes.forEach((mod, i) => {
      const x = 40 + i * 100;
      mod.drawer(ctx, x + 10, y, 60, primaryColor);
      ctx.fillStyle = '#888';
      ctx.font = '10px monospace';
      ctx.fillText(mod.type, x + 10, y + 76);
    });
    y += 100;

    // Section: Assembly
    ctx.fillStyle = '#888';
    ctx.font = '11px monospace';
    ctx.fillText('ASSEMBLY', 40, y);
    y += 20;

    const cellSize = Math.floor(28 * moduleScale);
    drawGrid(ctx, cellSize);
    renderModules(ctx, modules, cellSize, 40, y, primaryColor);
    y += rows * cellSize + 30;

    // Section: Typography Sample
    ctx.fillStyle = '#888';
    ctx.font = '11px monospace';
    ctx.fillText('MODULAR TYPOGRAPHY', 40, y);
    y += 20;

    if (uniqueTypes[0]) {
      const drawMod = (ctx2, x2, y2, size) => {
        uniqueTypes[0].drawer(ctx2, x2, y2, size * 0.9, primaryColor);
      };
      renderBitmapText(ctx, 'ABCDEFG', drawMod, 8, 40, y, 1);
      y += 80;
      renderBitmapText(ctx, 'HIJKLMN', drawMod, 8, 40, y, 1);
      y += 80;
    }

    // Footer
    ctx.fillStyle = primaryColor;
    ctx.fillRect(40, height - 60, width - 80, 1);
    ctx.fillStyle = '#666';
    ctx.font = '10px monospace';
    ctx.fillText('Generated by Flexible Visual Systems', 40, height - 40);
    ctx.fillText(new Date().toISOString().split('T')[0], width - 140, height - 40);

    downloadCanvas(canvas, 'fvs-system-sheet.png');
  }, [modules, rows, cols, primaryColor, secondaryColor, bgColor, moduleScale]);

  return (
    <button
      className="btn btn-primary"
      onClick={handleExport}
      disabled={!modules}
      title={modules ? 'Export system sheet as PNG' : 'Extract modules first'}
    >
      Export System Sheet
    </button>
  );
}
